version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: intellifill
      POSTGRES_USER: intellifill
      POSTGRES_PASSWORD: ${DB_PASSWORD:-intellifill123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intellifill"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://intellifill:${DB_PASSWORD:-intellifill123}@postgres:5432/intellifill
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-refresh-secret-key-here}
      RATE_LIMIT_MAX: 100
      RATE_LIMIT_WINDOW: 15
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:delegated
      - ./package.json:/app/package.json:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
      - ./nodemon.json:/app/nodemon.json:delegated
      # Data volumes
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ./logs:/app/logs
      # Exclude node_modules to use container's dependencies
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev:worker
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://intellifill:${DB_PASSWORD:-intellifill123}@postgres:5432/intellifill
      REDIS_URL: redis://redis:6379
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:delegated
      - ./package.json:/app/package.json:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
      # Data volumes
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./models:/app/models
      # Exclude node_modules
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: http://localhost:3000/api
    volumes:
      - ./web/src:/app/src:delegated
      - ./web/public:/app/public:delegated
      - ./web/package.json:/app/package.json:delegated
      - ./web/vite.config.ts:/app/vite.config.ts:delegated
      - /app/node_modules
    ports:
      - "3001:5173"  # Vite dev server port
    depends_on:
      - app
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data:
  redis_data: